### ISSUE TITLE
Can't load pretrained model

### ISSUE THREAD

**Issue by wshuang808** [OniroAI/Semantic-segmentation-with-MobileNetV3#7]
Hi, thanks for the project. It's really interesting to play and learn from it. However I got `ValueError: Shapes (1, 1, 24, 2) and (1, 1, 24, 1) are incompatible` when trying to load the pretrained model. Seems like it has some problem while loading weights from the model. I also noticed that you mentioned the pretrained model was trained with TF2.0. Could that be the cause of this issue? I am with TF2.3 btw.

**Comment by wshuang808** [comment]
I managed to figure out the reason. It because I changed the n_class=2.

**Comment by voeykovroman** [comment]
Was going to take a look during the weekend, but you've already solved it! Thanks! Yes, the thing was to pass the correct parameters to the model constructor to load the pretrained models (which were built with the parameters you can find in the training notebook)
