### ISSUE TITLE
Train with GPU

### ISSUE THREAD

**Issue by w-okada** [OniroAI/Semantic-segmentation-with-MobileNetV3#8]
Thanks for the great work!
Your model can do inference with very high fps!

I am trying to train model with your train code. And I found the process is very slow and does not use GPU.
I read your code and I found the line where GPU is enabled is commented out. 

```
    def fit(self, best_on_val=True):
        # with tf.device(self.device):
```

1. Why did you comment out the GPU line?
2. I have modified the line to enable the GPU, but the process doesn't become fast. (GPU usage is about 10% or so with RTX 2080Ti). Do you have any idea about it?

**Comment by voeykovroman** [comment]
Hey @w-okada, thank you! 
Sorry for the late response.
1) It's hard to remember the details of this project but commenting out this line most likely was unintentional and should be fixed
2) Yeah, GPU utilisation won't be high for several reasons: depth-wise separable convolutions are not optimized for GPU (the main target of this blocks is mobile devices); the bottleneck is data-preparation (loading and augmenting images takes more time than forward and backward paths of the network and mainly depend on HDD(SSD) and CPU.

**Comment by w-okada** [comment]
Thank you.
I study your code more.
